name: Publish to pub.dev

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.0'
          channel: 'stable'
      
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Format code
        run: dart format . --set-exit-if-changed
      
      - name: Analyze project source
        run: flutter analyze
      
      - name: Run tests
        run: flutter test --coverage
      
      - name: Publish to pub.dev
        uses: k-paxian/dart-package-publisher@v1.5.1
        with:
          accessToken: ${{ secrets.PUBLISH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.PUBLISH_REFRESH_TOKEN }}
          skipTest: false
          suppressBuildRunner: false
